model = {
    "timestamp":[],
    "smac":[],
    "dmac":[],
    "ipId": [],
    "ttl": [],
    "sip": [],
    "dip": [],
    "sport": [],
    "dport": [],
    "msslen": [],
    "rseq": [],
    "rack": [],
    "nseq": [],
    "flags_reset": [],
    "flags_cwr": [],
    "flags_urg": [],
    "flags_ack": [],
    "flags_push": [],
    "flags_syn": [],
    "flags_fin": []
}